/* Generated By:JJTree: Do not edit this line. ASTCONCAT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package REGEX;

public
class ASTCONCAT extends SimpleNode {
  public ASTCONCAT(int id) {
    super(id);
  }

  public ASTCONCAT(EG2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4fc890d3bfb6070db1fe65f27081b46 (do not edit this line) */
