/* Generated By:JJTree: Do not edit this line. ASTGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package REGEX;

public
class ASTGroup extends SimpleNode {
  public ASTGroup(int id) {
    super(id);
  }

  public ASTGroup(EG2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9058cbf209a585e982a4e27afe03f22e (do not edit this line) */
