/* Generated By:JJTree: Do not edit this line. ASTID_Node.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package REGEX;

public
class ASTID_Node extends SimpleNode {
	public String identifier;
  public ASTID_Node(int id) {
    super(id);
  }

  public ASTID_Node(EG2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=931d3835d63271a1a933521d120d4e72 (do not edit this line) */
