/* Generated By:JJTree: Do not edit this line. ASTID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package REGEX;

public
class ASTID extends SimpleNode {
  public ASTID(int id) {
    super(id);
  }

  public ASTID(EG2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=443305edb9fb265ec3dbbd0f7c874bb3 (do not edit this line) */
