/* Generated By:JJTree: Do not edit this line. ASTOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package REGEX;

public
class ASTOR extends SimpleNode {
  public ASTOR(int id) {
    super(id);
  }

  public ASTOR(EG2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3f735a9ca37cf31b5c13e85919c5999c (do not edit this line) */
