/* Generated By:JJTree: Do not edit this line. ASTRegex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package REGEX;

public
class ASTRegex extends SimpleNode {
  public ASTRegex(int id) {
    super(id);
  }

  public ASTRegex(EG2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42949fb601abe983ad73eeb6c76b7c35 (do not edit this line) */
