/* Generated By:JJTree: Do not edit this line. ASTvoid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package REGEX;

public
class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(EG2 p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89a642c0d806c8a6b15f81586761c750 (do not edit this line) */
