/* Generated By:JJTree&JavaCC: Do not edit this line. EG2Constants.java */
package REGEX;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int QUANTIFIER_ANY = 9;
  /** RegularExpression Id. */
  int QUANTIFIER_ONEORMORE = 10;
  /** RegularExpression Id. */
  int QUANTIFIER_ZEROORONE = 11;
  /** RegularExpression Id. */
  int QUANTIFIER_NRFIXED = 12;
  /** RegularExpression Id. */
  int QUANTIFIER_NRTOUNBOUND = 13;
  /** RegularExpression Id. */
  int QUANTIFIER_NRTONR = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER>",
    "<ID>",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "<QUANTIFIER_NRFIXED>",
    "<QUANTIFIER_NRTOUNBOUND>",
    "<QUANTIFIER_NRTONR>",
  };

}
