/* Generated By:JJTree&JavaCC: Do not edit this line. EG2Constants.java */
package REGEX;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int QUANTIFIER_ANY = 6;
  /** RegularExpression Id. */
  int QUANTIFIER_ONEORMORE = 7;
  /** RegularExpression Id. */
  int QUANTIFIER_ZEROORONE = 8;
  /** RegularExpression Id. */
  int QUANTIFIER_NRFIXED = 9;
  /** RegularExpression Id. */
  int QUANTIFIER_NRTOUNBOUND = 10;
  /** RegularExpression Id. */
  int QUANTIFIER_NRTONR = 11;
  /** RegularExpression Id. */
  int LP = 12;
  /** RegularExpression Id. */
  int RP = 13;
  /** RegularExpression Id. */
  int DOT = 14;
  /** RegularExpression Id. */
  int LF = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<INTEGER>",
    "<ID>",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "<QUANTIFIER_NRFIXED>",
    "<QUANTIFIER_NRTOUNBOUND>",
    "<QUANTIFIER_NRTONR>",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"\\n\"",
    "\"|\"",
  };

}
