/* Generated By:JavaCC: Do not edit this line. EG2TreeConstants.java Version 5.0 */
package REGEX;

public interface EG2TreeConstants
{
  public int JJTREGEX = 0;
  public int JJTQUANTIFIER = 1;


  public String[] jjtNodeName = {
    "Regex",
    "Quantifier",
  };
}
/* JavaCC - OriginalChecksum=3accc97ba675e98bcf63839eb2252b97 (do not edit this line) */
